spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rebuild_tmall?characterEncoding=utf-8&useUnicode=true&autoReconnect=true&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
    
    
  mvc: 
    static-path-pattern: /**
    
    
  velocity:
    content-type: text/html; charset=utf-8    
    
    
    
    
    
    
    
server:
  port: 8095



mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
    
wechat: 
  mpAppId: wx4573a9e9e4e7f8cf
  mpAppSecret: 412a365b2734af961ec492aeb7b857af
  